[build]
  base = "frontend"
  command = "rm -rf node_modules package-lock.json && npm install && CI=false npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 